### ISSUE TITLE
Final stages

### ISSUE THREAD

**Issue by wendtke** [wendtke/homicide_hw_5#6]
@kaycwill @awalz7626 
Do either of you need anything from me over the next few days? 

Do I need to change Plot 3 in any way? 

Let me know when your parts are finalized, and I can email Dr. Anderson with the PDF output and GitHub link. I can copy you, if you send your email addresses.

**Comment by kaycwill** [comment]
Hi, 
I'm finished with my piece of Homework 5. 

Let me know if you think there needs to be any changes.

My email is kayla.williams@colostate.edu

Thank you!

**Comment by wendtke** [comment]
It looks great!! 

I will copy you on the email to Dr. Anderson.
